/**
 * AUTO-GENERATED. DO NOT EDIT.
 *
 * This file is automatically generated by tools/scripts/generate-runtime-paths.ts
 * Source: tsconfig.base.json compilerOptions.paths
 *
 * To regenerate:
 *   pnpm nx run infra-runtime-paths:gen:runtime-paths
 *
 * Do not modify this file manually. Your changes will be overwritten.
 */

import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { register } from 'tsconfig-paths';

/**
 * Runtime path mappings derived from tsconfig.base.json.
 * TypeScript paths (.ts/.tsx) have been converted to JavaScript (.js).
 */
const runtimePaths: Record<string, string[]> = {
  "@klastack-nx/api/auth": [
    "libs/api/auth/src/index.js"
  ],
  "@klastack-nx/api/client": [
    "libs/web/api-client/src/index.js"
  ],
  "@klastack-nx/api/stats": [
    "libs/api/stats/src/index.js"
  ],
  "@klastack-nx/api/tenancy": [
    "libs/api/tenancy/src/index.js"
  ],
  "@klastack-nx/api/users": [
    "libs/api/users/src/index.js"
  ],
  "@klastack-nx/infra/database": [
    "libs/infra/database/src/index.js"
  ],
  "@klastack-nx/infra/runtime-paths": [
    "libs/infra/runtime-paths/src/index.js"
  ],
  "@klastack-nx/shared/tailwind": [
    "libs/shared/tailwind/src/index.js"
  ],
  "@klastack-nx/shared/tailwind/*": [
    "libs/shared/tailwind/src/*"
  ],
  "@klastack-nx/shared/users": [
    "libs/shared/users/src/index.js"
  ],
  "@klastack-nx/web-ui/*": [
    "libs/web/ui/src/*"
  ],
  "@klastack-nx/web/auth": [
    "libs/web/auth/src/index.js"
  ],
  "@klastack-nx/web/state": [
    "libs/web/state/src/index.js"
  ],
  "@klastack-nx/web/ui": [
    "libs/web/ui/src"
  ]
};

/**
 * Robustly compute the workspace dist root directory.
 *
 * Strategy (in order):
 * 1. Use NX_WORKSPACE_ROOT env var if available (Nx standard)
 * 2. Walk up from __dirname to find a directory containing dist/apps or dist/libs
 * 3. Walk up from process.cwd() to find a directory containing dist/
 * 4. Fail with descriptive error
 */
function computeDistRoot(): string {
  // Strategy 1: Prefer Nx-provided workspace root
  const workspaceRoot = process.env['NX_WORKSPACE_ROOT'];
  if (workspaceRoot) {
    return resolve(workspaceRoot, 'dist');
  }

  // Strategy 2: Walk up from __dirname to find workspace with dist/apps or dist/libs
  let current = __dirname;
  for (let i = 0; i < 10; i++) {
    const distPath = resolve(current, 'dist');
    const distApps = resolve(distPath, 'apps');
    const distLibs = resolve(distPath, 'libs');
    
    if (existsSync(distApps) || existsSync(distLibs)) {
      return distPath;
    }

    const parent = resolve(current, '..');
    if (parent === current) break; // Reached filesystem root
    current = parent;
  }

  // Strategy 3: Walk up from cwd to find dist folder
  current = process.cwd();
  for (let i = 0; i < 10; i++) {
    const candidate = resolve(current, 'dist');
    if (existsSync(candidate)) {
      return candidate;
    }

    const parent = resolve(current, '..');
    if (parent === current) break;
    current = parent;
  }

  // Strategy 4: Fail with helpful message
  throw new Error(
    [
      'Unable to locate workspace dist directory.',
      'Tried: NX_WORKSPACE_ROOT env var, walking up from __dirname, walking up from cwd.',
      'Ensure you are running from within the workspace, or set NX_WORKSPACE_ROOT environment variable.',
    ].join(' ')
  );
}

/**
 * Register TypeScript path aliases for runtime resolution.
 * This function is idempotent and safe to call multiple times.
 */
export function registerRuntimeTsPaths(): void {
  const g = globalThis as typeof globalThis & { __ks_ts_paths_registered__?: boolean };
  
  // Idempotent guard - prevent double registration
  if (g.__ks_ts_paths_registered__) {
    return;
  }

  const distRoot = computeDistRoot();
  register({ baseUrl: distRoot, paths: runtimePaths });

  g.__ks_ts_paths_registered__ = true;
}

// Auto-register on module load (side effect)
registerRuntimeTsPaths();
